blueprint:
  name: Refrigerator temperature control
  description: Control fridge temperature with a smart plug and temperature sensor
  domain: automation
  input:
    input_temperature:
      name: Input temperature sensor
      selector:
        entity:
          filter:
            - device_class: temperature
    smart_plug_switch:
      name: Smart plug switch
      selector:
        entity:
          filter:
            - domain: switch
    smart_plug_power:
      name: Smart plug power
      selector:
        entity:
          filter:
            - device_class: power
    max_temperature:
      name: Maximum temperatuur
      selector:
        entity:
          filter:
            - domain: input_number
    turn_off_temperature:
      name: Turn off temperature
      selector:
        entity:
          filter:
            - domain: input_number
    enable:
      name: Enable
      selector:
        entity:
          filter:
            - domain: input_boolean
  
trigger:
  - platform: state
    entity_id:
      - !input input_temperature

action:
 - if:
   - condition: numeric_state
     entity_id: !input input_temperature
     above: !input max_temperature
   then:
     - service: switch.turn_on
       target:
         entity_id: !input smart_plug_switch
       data: {}
 - if:
   - condition: numeric_state
     entity_id: !input input_temperature
     below: !input turn_off_temperature
   - condition: numeric_state
     entity_id: !input smart_plug_power
     below: 1
   then:
     - service: switch.turn_off
       target:
         entity_id: !input smart_plug_switch
       data: {}